[package]
name = "autopilot"
version = "0.2.1"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]
description = "A simple, cross-platform GUI automation library for Rust."
homepage = "https://www.autopy.org"
readme = "README.md"
repository = "https://github.com/autopilot-rs/autopilot-rs"
license = "Apache-2.0"
keywords = ["cross-platform", "gui" ,"automation", "input", "simulation"]
categories = [
    "api-bindings",
    "gui",
    "os::macos-apis",
    "os::unix-apis",
    "os::windows-apis"
]

[dependencies]
image = "0.22.2"
libc = "0.2.62"
rand = "0.7.0"
scopeguard = "1.0.0"

[dev-dependencies]
quickcheck = "0.9.0"

[build-dependencies]
pkg-config = "0.3.16"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6.4"
core-graphics = { version = "0.17.2", features = ["highsierra"] }
cocoa = "0.19.0"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.18.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["libloaderapi", "minwindef", "winbase", "winuser"] }
