[package]
name = "autopilot"
version = "0.1.0"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]
description = "A simple, cross-platform GUI automation library for Rust."
homepage = "https://www.autopy.org"
license = "Apache-2.0"
keywords = ["cross-platform", "gui" ,"automation"]
categories = [
    "api-bindings",
    "gui",
    "os",
    "os::macos-apis",
    "os::unix-apis",
    "os::windows-apis"
]

[dependencies]
image = "0.19"
libc = "0.2.40"
rand = "0.4.2"
scopeguard = "0.3.3"

[dev-dependencies]
quickcheck = "*"

[build-dependencies]
pkg-config = "0.3.11"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.5.1"
core-graphics = "0.13.0"
cocoa = "0.14.0"

[target.'cfg(target_os = "linux")'.dependencies]
x11 = "2.17.5"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["libloaderapi", "minwindef", "winbase", "winuser"] }
